# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-01 04:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(default='', max_length=250),
        ),
    ]
