# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-01 06:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20160701_0457'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('started', 'Started'), ('released', 'Released')], default='started', max_length=15),
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(default='', max_length=250, unique=True),
        ),
    ]
