# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-01 07:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_project_start_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='description',
            new_name='summary',
        ),
    ]
