# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-01 07:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20160701_0718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='summary',
            field=models.TextField(max_length=500),
        ),
    ]
