# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-01 07:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20160701_0724'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(default='To be completed'),
            preserve_default=False,
        ),
    ]
